#
# Module manifest for module 'cMachineConfig' 
#

# Generated by: Alexis.Coles
#
# Generated on: 24/04/2017
#

@{
	# Script module or binary module file associated with this manifest.
	RootModule = 'cMachineConfig.psm1'

	# Version number of this module.
	ModuleVersion = '1.0.0'

	# ID used to uniquely identify this module
	GUID = '9f9d559c-3861-480e-a948-37b40b647b72'

	# Author of this module
	Author = 'Alexis.Coles'

	# Company or vendor of this module
	CompanyName = 'Spreadex Ltd'

	# Copyright statement for this module
	Copyright = '(c) 2015 Alexis.Coles. All rights reserved.'

	# Description of the functionality provided by this module
	Description = 'resource module for managing machine.config files'

	# Functions to export from this module
	FunctionsToExport = '*'

	# Cmdlets to export from this module
	CmdletsToExport = '*'

	# Variables to export from this module
	VariablesToExport = '*'

	# Aliases to export from this module
	AliasesToExport = '*'

	# DSC resources to export from this module
	DscResourcesToExport = 'cMachineKey'

	PrivateData = @{
		PSData = @{
		}
	}
}
